### ISSUE TITLE
Where are the three models, TCSinger, SAPostnet and SDLM?  

### ISSUE THREAD

**Issue by OhMyGod32** [AaronZ345/TCSinger#2]
I couldn't find the TCSinger, SAPostnet, and SDLM models

**Comment by AaronZ345** [comment]
I'm pretty occupied lately. I require a certain amount of time for desensitization and training. Perhaps the checkpoint will be released some time later.

**Comment by AaronZ345** [comment]
I have updated the code and the checkpoint.
